const bagCatalogue = [
  // We need to have all the products here with (productType: bag or productType: shoe)
    {
      bagID: 0,
      productType: 'hand bag',
      bagImage: 'Neverfull.jpg',
      bagName: 'Neverfull',
      bagBrand: 'Louis Vuitton',
      bagColor: 'brown',
      price: 28000,
    },
    {
      bagID: 1,
      productType: 'hand bag',
      bagImage: 'ClassicFlapBag.jpeg',
      bagName: 'Classic Flap Bag',
      bagBrand: 'Chanel',
      bagColor: 'brown, black, white',
      price: 45000,
    },
    {
      bagID: 2,
      productType: 'hand bag',
      bagImage: 'Birkin.jpeg',
      bagName: 'Birkin',
      bagBrand: 'Hermès',
      bagColor: 'brown, black, white',
      price: 32000,
    },
    {
      bagID: 3,
      productType: 'hand bag',
      bagImage: 'CityBag.png',
      bagName: 'City Bag',
      bagBrand: 'Balenciaga',
      bagColor: 'red, black',
      price: 56000,
    },
    {
      bagID: 4,
      productType: 'hand bag',
      bagImage: 'LadyDior.jpeg',
      bagName: 'Lady Dior',
      bagBrand: 'Dior',
      bagColor: 'White, black',
      price: 47000,
    },
    {
      bagID: 5,
      productType: 'hand bag',
      bagImage: 'SohoDiscoBag.jpeg',
      bagName: 'Soho Disco Bag',
      bagBrand: 'Gucci',
      bagColor: 'Brown, gold',
      price: 39500,
    },
    {
      bagID: 6,
      productType: 'hand bag',
      bagImage: 'Speedy.jpg',
      bagName: 'Speedy',
      bagBrand: 'Louis Vuitton',
      bagColor: 'Brown',
      price: 45500,
    },
    {
      bagID: 7,
      productType: 'hand bag',
      bagImage: 'redSmarkBag.jpg',
      bagName: 'Faye',
      bagBrand: 'Chloé',
      bagColor: 'Red',
      price: 89500,
    },
    {
      bagID: 8,
      productType: 'hand bag',
      bagImage: 'peeroBags.jpeg',
      bagName: 'Antigona',
      bagBrand: 'Givenchy',
      bagColor: 'White',
      price: 78000,
    },
    {
      bagID: 9,
      productType: 'hand bag',
      bagImage: 'prada.png',
      bagName: 'Luggage Tote',
      bagBrand: 'Celine',
      bagColor: 'Brown, Black',
      price: 78000,
    },
    {
      bagID: 10,
      productType: 'dress',
      bagImage: 'BaqcunreSexyoutfit.png',
      bagName: 'Baqcunre Sexy outfit',
      bagBrand: 'Baqcunre',
      bagColor: 'Red, Black',
      price: 27500,
    },
    {
      bagID: 11,
      productType: 'dress',
      bagImage: 'CocktailSwingDress.jpg',
      bagName: 'Cocktail swing dress',
      bagBrand: 'Ofmuch',
      bagColor: 'White, Black',
      price: 35500,
    },
    {
      bagID: 12,
      productType: 'dress',
      bagImage: 'DinaDress.jpg',
      bagName: 'Dina Dress',
      bagBrand: 'Dolce Giovanni',
      bagColor: 'Grey, purple',
      price: 52500,
    },
    {
      bagID: 13,
      productType: 'dress',
      bagImage: 'ElegantOffice.png',
      bagName: 'Elegant Office',
      bagBrand: 'Dolce Giovanni',
      bagColor: 'Grey',
      price: 50500,
    },
    {
      bagID: 14,
      productType: 'dress',
      bagImage: 'HiQueen.jpg',
      bagName: 'Hi Queen',
      bagBrand: 'Barbour White Label',
      bagColor: 'Red',
      price: 90000,
    },
    {
      bagID: 15,
      productType: 'dress',
      bagImage: 'Highcollardress.png',
      bagName: 'High collar dress',
      bagBrand: 'Genevieve Sweeney',
      bagColor: 'Black, white',
      price: 9000,
    },
    {
      bagID: 16,
      productType: 'dress',
      bagImage: 'Lazirosummervintage.jpg',
      bagName: 'Laziro summer vintage',
      bagBrand: 'Genevieve Sweeney',
      bagColor: 'Black, white',
      price: 16000,
    },
    {
      bagID: 17,
      productType: 'dress',
      bagImage: 'LongSleeveDenim.jpg',
      bagName: 'Long Sleeve Denim',
      bagBrand: 'Community Clothing',
      bagColor: 'Denim',
      price: 35000,
    },
    {
      bagID: 18,
      productType: 'dress',
      bagImage: 'Narrowdestiny.jpg',
      bagName: 'Narrow destiny',
      bagBrand: 'AXEL ARIGATO',
      bagColor: 'Black',
      price: 45000,
    },
    {
      bagID: 19,
      productType: 'dress',
      bagImage: 'TurkeyLovelydress.jpg',
      bagName: 'Turkey Lovely',
      bagBrand: 'AXEL ARIGATO',
      bagColor: 'Brown',
      price: 45000,
    },
    {
      bagID: 20,
      productType: 'dress',
      bagImage: 'Slimcutdress.jpeg',
      bagName: 'Slim cut dress.jpeg',
      bagBrand: 'DKNY',
      bagColor: 'Red, Navy blue',
      price: 67000,
    },
    {
      bagID: 21,
      productType: 'dress',
      bagImage: 'Reddress.jpg',
      bagName: 'Maison Magiela',
      bagBrand: 'Chloe',
      bagColor: 'Red',
      price: 99000,
    },
    {
      bagID: 22,
      productType: 'dress',
      bagImage: 'SwingAudrey.jpg',
      bagName: 'Swing Audrey',
      bagBrand: 'DKNY',
      bagColor: 'Blue Black',
      price: 56000,
    },
    {
      bagID: 23,
      productType: 'dress',
      bagImage: 'printed-satin-blouse.jpg',
      bagName: 'Printed satin blouse',
      bagBrand: 'DKNY',
      bagColor: 'Yellow, White Black',
      price: 23000,
    },
    {
      bagID: 24,
      productType: 'shoes',
      bagImage: 'Casualsingles.jpg',
      bagName: 'Casual singles',
      bagBrand: 'Meadows',
      bagColor: 'White',
      price: 33000,
    },
    {
      bagID: 25,
      productType: 'shoes',
      bagImage: 'GoldenBest.jpeg',
      bagName: 'Golden Best',
      bagBrand: 'Barbour White Label',
      bagColor: 'Gold',
      price: 45000,
    },
    {
      bagID: 26,
      productType: 'shoes',
      bagImage: 'HighheeledPumpsuede.jpg',
      bagName: 'High heeled Pump suede.jpg',
      bagBrand: 'Barbour White Label',
      bagColor: 'Black, Brown',
      price: 29500,
    },
    {
      bagID: 27,
      productType: 'shoes',
      bagImage: 'KatyPerry.png',
      bagName: 'Katy Perry',
      bagBrand: 'Katy Perry',
      bagColor: 'Blue',
      price: 69900,
    },
    {
      bagID: 28,
      productType: 'shoes',
      bagImage: 'LaceupHollow.png',
      bagName: 'Laceup Hollow',
      bagBrand: 'Genevieve Sweeney',
      bagColor: 'White',
      price: 15000,
    },
    {
      bagID: 29,
      productType: 'shoes',
      bagImage: 'Macys.png',
      bagName: 'Macys',
      bagBrand: 'A Piedi',
      bagColor: 'Pink Rose, Brown',
      price: 45000,
    },
    {
      bagID: 30,
      productType: 'shoes',
      bagImage: 'OrthoShoes.png',
      bagName: 'Ortho Shoes',
      bagBrand: 'Castore',
      bagColor: 'Black, White',
      price: 38000,
    },
    {
      bagID: 31,
      productType: 'shoes',
      bagImage: 'Pumpheels.jpg',
      bagName: 'Pump heels',
      bagBrand: 'A Piedi',
      bagColor: 'Black, Brown',
      price: 41000,
    },   
    {
      bagID: 32,
      productType: 'shoes',
      bagImage: 'Safa.jpeg',
      bagName: 'Safa',
      bagBrand: 'Katy Perry',
      bagColor: 'Black, Grey',
      price: 22000,
    },
    {
      bagID: 33,
      productType: 'shoes',
      bagImage: 'SamilorBowFlats.jpg',
      bagName: 'Samilor Bow Flats',
      bagBrand: 'Good News',
      bagColor: 'Black, Brown',
      price: 29550,
    },
    {
      bagID: 34,
      productType: 'shoes',
      bagImage: 'SolidFlats.jpg',
      bagName: 'Solid Flats',
      bagBrand: 'Good News',
      bagColor: 'Black, Brown',
      price: 42600,
    },
    {
      bagID: 35,
      productType: 'shoes',
      bagImage: 'workshoes.jpeg',
      bagName: 'Work shoes',
      bagBrand: 'Ofmuch',
      bagColor: 'Pink, Brown',
      price: 17800,
    },
   
  ];
export default bagCatalogue